### ISSUE TITLE
Review DACO TRA Documents

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/roadmap#6]
Review at high-level TRA documents from DACO as a reference

Compare recommendations and our responses to our design for OHCRN

**Comment by mistryrn** [comment]
Added some initial takeaways from reviewing the DACO TRA documents to the wiki here: https://wiki.oicr.on.ca/display/OHCRN/DACO+TRA+Takeaways

**Comment by b-f-chan** [comment]
Again, close after meeting witih Jon on Aug 10, if no further issues

**Comment by b-f-chan** [comment]
Review done no further major issues found at this point
